import { useEffect, useState }
from "react";
import { useNavigate }
from "react-router-dom";
import axios from "axios";
import jsPDF from "jspdf";
import { useParams }
from "react-router-dom";

import ReactMarkdown
from "react-markdown";

function SummaryPage() {
  const navigate =
  useNavigate();
  const { id } = useParams();

  const [summary, setSummary] =
    useState("");
const [language,
setLanguage] =
  useState("English");
  const [loading, setLoading] =
    useState(true);
  const [progress,
setProgress] =
  useState(0);

const [status,
setStatus] =
  useState("Preparing AI analysis...");
const downloadPDF = () => {

  const doc = new jsPDF();

  // PAGE WIDTH

  const pageWidth =
    doc.internal.pageSize.width;

  // TITLE

  doc.setFillColor(37, 99, 235);

  doc.rect(
    0,
    0,
    pageWidth,
    35,
    "F"
  );

  doc.setTextColor(255, 255, 255);

  doc.setFontSize(22);

  doc.setFont(
    "helvetica",
    "bold"
  );

  doc.text(
    "AI Generated Study Notes",
    20,
    22
  );
doc.setFontSize(10);

doc.setTextColor(
  220,
  220,
  220
);

doc.text(
  "Generated by AI Research Assistant",
  20,
  30
);
  // RESET TEXT COLOR

  doc.setTextColor(30, 41, 59);
doc.setDrawColor(
  200,
  200,
  200
);

doc.line(
  20,
  40,
  190,
  40
);
  // CLEAN MARKDOWN

  const cleanText =

    summary

      .replace(/#/g, "")

      .replace(/\*/g, "•")

      .replace(/`/g, "")

      .replace(/>/g, "");

  // SPLIT TEXT

  const splitText =
    doc.splitTextToSize(
      cleanText,
      170
    );

  // BODY TEXT

  doc.setFontSize(12);

  doc.setFont(
    "times",
    "normal"
  );

  let y = 50;

  splitText.forEach((line) => {

  // NEW PAGE

  if (y > 270) {

    addFooter(doc);

    doc.addPage();

    y = 30;
  }

  // DETECT HEADINGS

  if (

    line.length < 45 &&

    (
      line.includes("Introduction") ||
      line.includes("Summary") ||
      line.includes("Conclusion") ||
      line.includes("Qualification") ||
      line.includes("Skills") ||
      line.includes("Projects") ||
      line.includes("Experience")
    )

  ) {

    // HEADING COLOR

    doc.setFont(
      "helvetica",
      "bold"
    );

    doc.setTextColor(
      37,
      99,
      235
    );

    doc.setFontSize(15);

    doc.text(
      line,
      20,
      y
    );

    y += 10;

    // RESET

    doc.setFontSize(12);

    doc.setFont(
      "times",
      "normal"
    );

    doc.setTextColor(
      30,
      41,
      59
    );

  } else {

    doc.text(
      line,
      20,
      y
    );

    y += 8;
  }
});

  // FOOTER

  addFooter(doc);

  // SAVE

  doc.save(
    "AI_Study_Notes.pdf"
  );
};
const translateSummary =
  async (selectedLanguage) => {

    try {

      setLoading(true);

      const response =
        await axios.post(

          "http://localhost:5000/api/ai/translate",

          {

            text: summary,

            language:
              selectedLanguage,
          }
        );

      setSummary(
        response.data.translation
      );

      setLanguage(
        selectedLanguage
      );

      setLoading(false);

    } catch (error) {

      console.log(error);

      setLoading(false);
    }
  };
// FOOTER FUNCTION

const addFooter = (doc) => {

  const pageCount =
    doc.getNumberOfPages();

  for (
    let i = 1;
    i <= pageCount;
    i++
  ) {

    doc.setPage(i);

    doc.setFontSize(10);

    doc.setTextColor(
      120
    );

    doc.text(

      `Generated by AI Research Assistant | Page ${i}`,

      20,

      290
    );
  }
};
  // FETCH SUMMARY
useEffect(() => {

  const fetchSummary =
    async () => {

      try {

        const token =
          localStorage.getItem(
            "token"
          );
const historyResponse =
  await axios.get(

    "http://localhost:5000/api/history",

    {
      headers: {

        Authorization:
          `Bearer ${token}`,
      },
    }
  );

let selectedFile =

  historyResponse.data.find(
    (item) =>
      item._id === id
  );

if (
  selectedFile &&
  !selectedFile.summary
) {

  setStatus(
    "Generating AI summary..."
  );

  setProgress(30);

  await axios.post(

    `http://localhost:5000/api/ai/summary/${id}`,

    {},

    {
      headers: {

        Authorization:
          `Bearer ${token}`,
      },
    }
  );

  setStatus(
    "Finalizing summary..."
  );

  setProgress(80);

  // FETCH UPDATED DATA

  const updatedResponse =
    await axios.get(

      "http://localhost:5000/api/history",

      {
        headers: {

          Authorization:
            `Bearer ${token}`,
        },
      }
    );

 
  selectedFile =

    updatedResponse.data.find(
      (item) =>
        item._id === id
    );
}


        console.log(selectedFile);

        if (selectedFile) {

          setSummary(
            selectedFile.summary
          );
setProgress(100);

setStatus(
  "Summary Ready 🚀"
);
        } else {

          setSummary(
            "Summary not found"
          );
        }

        setLoading(false);

      } catch (error) {

        console.log(error);

        setLoading(false);
      }
    };

  fetchSummary();

}, [id]);

  return (

   <div
  className="container-fluid py-4"
  style={{

    minHeight: "100vh",

    background:
      "linear-gradient(135deg,#020617,#0f172a,#111827)",

    paddingInline: "20px",
  }}
>
<button
  className="btn mb-4"

  onClick={() =>
    navigate(-1)
  }

  style={{

    background:
      "#1e293b",

    color: "white",

    border:
      "1px solid rgba(255,255,255,0.12)",

    borderRadius: "10px",

    padding: "10px 18px",

    fontWeight: "600",
  }}
>

  ← Back

</button>
    <div
  className="d-flex flex-column flex-md-row justify-content-between align-items-start align-items-md-center gap-3 mb-4"
>

  <h2
    className="fw-bold"
    style={{
      color: "white",
    }}
  >

    AI Summary

  </h2>

  <div
    className="d-flex flex-column flex-sm-row gap-3 w-100 w-md-auto"
  >

    <select

      value={language}

      onChange={(e) =>

        translateSummary(
          e.target.value
        )
      }

      style={{

        padding: "10px 14px",

        borderRadius: "12px",

        background:
          "#1e293b",

        color: "white",

        border:
          "1px solid rgba(255,255,255,0.1)",

        minWidth: "140px",
      }}
    >

      <option>
        English
      </option>

      <option>
        Tamil
      </option>

      <option>
        Hindi
      </option>

      <option>
        French
      </option>

    </select>

    <button

      className="btn"

      onClick={downloadPDF}

      style={{

        background:
          "linear-gradient(90deg,#38bdf8,#2563eb)",

        color: "white",

        border: "none",

        borderRadius: "12px",

        padding: "10px 18px",

        fontWeight: "600",

        whiteSpace: "nowrap",
      }}
    >

      ⬇ Download PDF

    </button>

  </div>

</div>

      {loading ? (

        <div
  className="text-center py-5"
>

  <h3
    className="text-white mb-4"
  >

    AI is analyzing your PDF 🚀

  </h3>

  <div
    style={{

      height: "14px",

      background:
        "rgba(255,255,255,0.08)",

      borderRadius: "20px",

      overflow: "hidden",

      maxWidth: "500px",

      margin: "auto",
    }}
  >

    <div

      style={{

        width:
          `${progress}%`,

        height: "100%",

        background:
          "linear-gradient(90deg,#38bdf8,#2563eb)",

        transition:
          "0.4s",
      }}
    />
  </div>

  <p
    className="text-info mt-4"
  >

    {status}

  </p>

  <p
    className="text-secondary"
  >

    Large PDFs may take
    1–3 minutes

  </p>

</div>

      ) : (

        <div
          className="shadow border-0 p-4"
         style={{
  borderRadius: "20px",

  background:
    "rgba(255,255,255,0.08)",

  backdropFilter:
    "blur(12px)",

  color: "white",

  border:
    "1px solid rgba(255,255,255,0.08)",
}}
        >

          <ReactMarkdown>

            {summary}

          </ReactMarkdown>

        </div>
      )}

    </div>
  );
}

export default SummaryPage;